version: "3.8"
services:
  app-node:
    image: node:lts-alpine
    container_name: app-back-node
    entrypoint:
      - "sh"
      - "-c"
      - "npm install && npm start"
    working_dir: /app
    ports:
      - 3600:3600
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: huayre
      MONGO_INITDB_ROOT_PASSWORD: huayre-password
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: huayre
      ME_CONFIG_MONGODB_ADMINPASSWORD: huayre-password
      ME_CONFIG_MONGODB_URL: mongodb://huayre:huayre-password@mongo:27017/
    depends_on:
      - mongo